### ISSUE TITLE
Method not found: 'Void Telegram.Bot.Requests.GetUpdatesRequest.set_Offset(Int32)'.

### ISSUE THREAD

**Issue by PavlMais** [TelegramBots/Telegram.Bot#1011]
# I found a bug to report

### Steps to reproduce
**Install dependencies**

Telegram.Bot **17.0.0-alpha.1** 
Telegram.Bot.Extensions.Polling 0.2.0

**Start receive updates**
```csharp
bot.StartReceiving(new DefaultUpdateHandler(HandleUpdateAsync, HandleErrorAsync), CancellationToken.None);
```

### Expected  behavior
  Works properly
### Actual behavior
```
System.MissingMethodException: Method not found: 'Void Telegram.Bot.Requests.GetUpdatesRequest.set_Offset(Int32)'.
   at Telegram.Bot.TelegramBotClientPollingExtensions.ReceiveAsync(ITelegramBotClient botClient, IUpdateHandler updateHandler, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Telegram.Bot.TelegramBotClientPollingExtensions.ReceiveAsync(ITelegramBotClient botClient, IUpdateHandler updateHandler, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClientPollingExtensions.<>c__DisplayClass1_0.<<StartReceiving>b__0>d.MoveNext()
```

### Environment data

**NuGet Package Version:** -

**.NET Version:** Core 5.0.205, Mono 6.12.0

**IDE:** Rider 2021.1.5

**App:** ASPNET.Core

**Comment by tuscen** [comment]
This is not a bug. Polling package `v0.2.0` is not compatible with `v17`. Latest polling package with `v17` support is not released yet.
