### ISSUE TITLE
The response ended prematurely.

### ISSUE THREAD

**Issue by anhro92** [TelegramBots/Telegram.Bot#1032]
sometime, i get this error when sending text message.

-------------------
EXCEPTION INFO
	Source: System.Net.Http
	Type: System.Net.Http.HttpRequestException
	TargetSite: Void MoveNext()
	Details: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)

**Comment by karb0f0s** [comment]
Internet is a vast space; everything can go wrong. If you need each request to be successful, you have to add a resiliency layer on top of `httpClient`, for example with Polly:
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly
or customizing `httpMessageHandler`
This way you can handle 429 or network layer-related errors.

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
