### ISSUE TITLE
Bot stoping recerve message

### ISSUE THREAD

**Issue by AugerSoft** [TelegramBots/telegram.bot#339]
Hi,
Thank you fro this lib. I have big problem...
I'm use Bot, ex:
```csharp
       var Bot = new TelegramBotClient(apiKey);
       Bot.OnMessage += Bot_OnMessage;
       Bot.StartReceiving();
        private static void Bot_OnMessage(object sender, Telegram.Bot.Args.MessageEventArgs e)
        {
            try
            {
                var message = e.Message;
                //some CODE
            }
            catch (Exception ex) {
                Log.logger.Fatal("Error:{0}", ex.Message);
                Log.logger.Fatal("Error:{0}", ex.StackTrace);
            }
            //throw new NotImplementedException();
        }
```
After 1-3 hours stops receiving messages...
Can I do something wrong?
May need to reconnect, when raise OnReceiveGeneralError or OnReceiveError?
NuGet Package Version:  10.4.0
.NET Version: 4.6
IDE: VS2015
App: Console App and ASP.NET MVC

**Comment by MrRoundRobin** [comment]
Are there some errors / exceptions logged?

**Comment by AugerSoft** [comment]
Error list is empty((

**Comment by AugerSoft** [comment]
this errors from OnReceiveGeneralError and OnReceiveError
```
2017-05-24 04:32:46.4355     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 04:32:46.4355     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 04:32:46.6416     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 04:32:46.6416     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 05:25:20.0010     ERROR    OnReceiveGeneralError: Response status code does not indicate success: 500 (Internal Server Error).
2017-05-24 05:25:20.0156     ERROR    OnReceiveGeneralError:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 05:25:22.6826     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 05:25:22.6826     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 05:25:22.8887     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 05:25:22.8887     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 05:25:23.0888     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 05:25:23.0888     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 05:25:23.2969     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 05:25:23.2969     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 05:25:23.4980     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 05:25:23.4980     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
2017-05-24 05:25:23.7119     ERROR    OnOnReceiveError: Invalid response received
2017-05-24 05:25:23.7119     ERROR    OnOnReceiveError:    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()
```

**Comment by MrDevIr** [comment]
Same issue.
Cannot recieve messages, Inline Query ,Callback Query.
`Exception thrown: 'System.ArgumentOutOfRangeException' in Telegram.Bot.dll
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Telegram.Bot.Types.Update.get_Type()
   at Telegram.Bot.TelegramBotClient.OnUpdateReceived(UpdateEventArgs e)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__54.MoveNext()`
Using Telegram.Bot 10.4.0

**Comment by parabola949** [comment]
@MrDevIr if you are using a `switch(update.Type)` check your default statement.  Most likely since you are using an older version, there is a new update type that you are not handling.  If using ReSharper, and you created the switch statement with that, the `case: default` is always to throw that exception.

**Comment by parabola949** [comment]
@AugerSoft sometimes Telegram has.. hiccups.  I'd recommend adding this to your on error method:
```if (!Bot.IsReceiving)
            {
                Bot.StartReceiving();
            }```

**Comment by MrDevIr** [comment]
@parabola949 Thanks, I just updated the package to newer (beta) version and the problem got solved

**Comment by pouladpld** [comment]
@AugerSoft You are using an old package. Use `.Core` package instead.
See why on  [project's README](https://github.com/TelegramBots/telegram.bot/blob/develop/README.md).
