### ISSUE TITLE
error in windows service bot for method GetFileAsync in computer that uses domain and proxy for internet

### ISSUE THREAD

**Issue by parvizwpf** [TelegramBots/telegram.bot#423]
hi
i use your library in a windows service project;
the system that bot is installed it uses domain and web proxy.
all things is perfect for example all text messages work fine and others work good.
even this code work fine on a system that has not domain access and proxy.
but when use GetFileAsync has error:
_______________________________________________
my code:
var file = StaticMembers.Bot.GetFileAsync(fileId);
file.Wait();
var fileResult = file.Result;
_________________________________________________
the Error:
Inner inner Error Message: An error occurred while sending the request.
Stack Trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<GetFileAsync>d__112.MoveNext()

**Comment by pouladpld** [comment]
@parvizwpf We have an [Issue Template](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md) here. Edit your post according to that so you give us more info about the situation.
