### ISSUE TITLE
GetFileAsync:  An error occurred while sending the request

### ISSUE THREAD

**Issue by parvizwpf** [TelegramBots/telegram.bot#427]
Inner inner Error Message: An error occurred while sending the request.
Stack Trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<GetFileAsync>d__112.MoveNext()

.net framework 4.6.2 installed + visual C++ Redutributable 2015 update 3 is installed

**Comment by pouladpld** [comment]
@parvizwpf If you still have the issue, feel free to open this again.
