### ISSUE TITLE
Problem with ParseMode enum deserialization

### ISSUE THREAD

**Issue by Tuscen** [TelegramBots/telegram.bot#462]
I have a problem with deserialization of `ParseMode` enum.

I store some messages in json on disk in this form:

```json
[
    {
        "type": "TextMessage",
        "parse_mode": "Markdown",
        "disable_web_page_preview": true,
        "disable_notification": false,
        "text": "Some markdown here"
    },
    {
        "type": "PhotoMessage",
        "disable_notification": false,
        "photo": "link to a photo"
    }
]
```

I deserialize this json to a list of my own class:

```csharp
public class Message
{
    [JsonProperty("type")]
    public MessageType Type { get; set; }

    [JsonProperty("text")]
    public string Text { get; set; }

    [JsonProperty("photo")]
    public string Photo { get; set; }

    [JsonProperty("audio")]
    public string Audio { get; set; }

    [JsonProperty("video")]
    public string Video { get; set; }

    [JsonProperty("voice")]
    public string Voice { get; set; }

    [JsonProperty("video_note")]
    public string VideoNote { get; set; }

    [JsonProperty("document")]
    public string Document { get; set; }

    [JsonProperty("duration")]
    public int Duration { get; set; }

    [JsonProperty("length")]
    public int Length { get; set; }

    [JsonProperty("performer")]
    public string Performer { get; set; }

    [JsonProperty("title")]
    public string Title { get; set; }

    [JsonProperty("width")]
    public int Width { get; set; }

    [JsonProperty("height")]
    public int Height { get; set; }

    [JsonProperty("parse_mode")]
    public ParseMode ParseMode { get; set; }

    [JsonProperty("caption")]
    public string Caption { get; set; }

    [JsonProperty("latitude")]
    public float Latitude { get; set; }

    [JsonProperty("longitude")]
    public float Longitude { get; set; }

    [JsonProperty("address")]
    public string Address { get; set; }

    [JsonProperty("foursquare_id")]
    public string FoursquareId { get; set; }

    [JsonProperty("phone_number")]
    public string PhoneNumber { get; set; }

    [JsonProperty("first_name")]
    public string FirstName { get; set; }

    [JsonProperty("last_name")]
    public string LastName { get; set; }

    [JsonProperty("disable_web_page_preview")]
    public bool DisableWebPagePreview { get; set; }

    [JsonProperty("disable_notification")]
    public bool DisableNotification { get; set; }
}
```

The problem is that `JsonConvert.DeserializeObject` throws an exception when it tries to deserialize `ParseMode` enum. For example, `MessageType` enum doesn't have this problem.

### Steps to reproduce

It's easy to reproduce.

This will be deserialized:

```csharp
JsonConvert.DeserializeObject<List<MessageType>>("[\"TextMessage\"]");
```

While this will throw an exception:

```csharp
JsonConvert.DeserializeObject<List<ParseMode>>("[\"Markdown\"]");
```

### Expected  behavior

I expect deserialized instance of `Message` class.

### Actual behavior

Here is the stack trace of the exception thrown during `List<ParseMode>` deserialization:

```
System.ArgumentException: The value "[Default, ]" is not of type "Telegram.Bot.Types.Enums.ParseMode" and cannot be used in this genericcollection.
Parameter name: value
   at System.ThrowHelper.ThrowWrongValueTypeArgumentException(Object value, Type targetType)
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract,JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
...
```

Here is the stack trace of the exception when I try to deserialize `List<Message>`:

```json
[
    {
        "type": "TextMessage",
        "parse_mode": "Markdown",
        "disable_web_page_preview": true,
        "disable_notification": false,
        "text":"'markdown markup here"
    }
]
```

```
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: :. Path '[0].parse_mode', line 5, position 34.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Telegram.Bot.Converters.ParseModeConverter.<>c__DisplayClass1_0.<ReadJson>b__0(KeyValuePair`2 mode)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Telegram.Bot.Converters.ParseModeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, TypeobjectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract,JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract,JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
...
```

*NuGet Package Version:* 13.2.0, 13.2.1
*.NET Version:* .NET Core 2.0
*IDE:* Project Rider, VS Code

**Comment by Olfi01** [comment]
You need to add Member serialization tags to the enum. Those aren't present in the files because we use a custom converter instead.

**Comment by Tuscen** [comment]
@Olfi01, thank you, `[JsonConverter(typeof(StringEnumConverter))]` helped. But why doesn't `MessageType` require this attribute? It can be deserialized from its string representation even without this attribute while `ParseMode` requires it. Actually I noticed that `MessageType` doesn't have a custom converter and `ParseMode` do have one. Maybe there is a problem in `ParseModeConverter` just as there was in `PhotoSizeConverter`?

**Comment by Olfi01** [comment]
No. MessageType isn't meant to be serialized in the first place, while ParseMode is bound to telegrams API.
