### ISSUE TITLE
InlineKeyboardButton are limited in InlineKeyboardMarkup ?

### ISSUE THREAD

**Issue by djary** [TelegramBots/telegram.bot#470]
Hi , I want create dynamic InlineKeyboardMarkup.

                  ` private static InlineKeyboardMarkup InlinePostsKeyboard;
                    private static List<string> PostsTitle;
                    ...
                    PostsTitle = (from p in dba.BlogPosts select p.Subject).Take(4).ToList();

                    var inlineButtons = PostsTitle.Select(title => new[] { InlineKeyboardButton.WithCallbackData(title, title) }).ToArray();
                    InlinePostsKeyboard = new InlineKeyboardMarkup(inlineButtons);

                      ...
                        Bot.SendTextMessageAsync(Chat.Id, e.Message.Text, replyMarkup: InlinePostsKeyboard);` 

as you see in above code bot most show 4 InlineKeyboardButton (per line) , but does not show anything !
Just enough change `....Take(4).ToList();` to 3 or less than 4 (ex : 3 , 2 or 1) and you will see that the buttons will be displayed correctly

I want to know the reason for this
Where have I made a mistake?

**Comment by djary** [comment]
get me this aggregate exception:
`System.AggregateException: One or more errors occurred. ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ArmanTelegramBotUpdateMethod.Program.Bot_OnMessage(Object sender, MessageEventArgs e) in C:\Users\Arman Es\documents\visual studio 2017\Projects\ArmanTelegramBotUpdateMethod\ArmanTelegramBotUpdateMethod\Program.cs:line 149
---> (Inner Exception #0) Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()<---`

**Comment by djary** [comment]
answer : https://stackoverflow.com/questions/46389040/inlinekeyboardbutton-are-limited-in-inlinekeyboardmarkup-telegram-bot-c-sharp
