### ISSUE TITLE
Large File

### ISSUE THREAD

**Issue by hamid67fathi** [TelegramBots/telegram.bot#476]
Im trying to upload files more than 50 mb but I encounter below error.
As I know Telegram is able to upload 1.5 Gb files
Telegram.Bot.Exceptions.ApiRequestException: Invalid response received ---> System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'ApiResponse`1' from content with media type 'text/html'.
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, IEnumerable`1 formatters, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__139`1.MoveNext()
   --- End of inner exception stack trace ---
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BillTelegramBot.Echo.Program.<BotOnMessageReceived>d__10.MoveNext() in

**Comment by pouladpld** [comment]
@hamid67fathi The file size limits for a user upload and a bot upload are different. This is written in tg bot API docs.

If you need more help, make sure you edit the post and follow the issue template.
