### ISSUE TITLE
Unable to serialize type Update with v13.3.0-rc1

### ISSUE THREAD

**Issue by Dragonsangel** [TelegramBots/telegram.bot#513]
I updated my NuGet package to v13.3.0-rc1 today to try out the new Live Location and ChatSticker functionality released in 3.4 and experienced the below issue when attempting to serialize incoming JSON.
Seems to be related to the changes in commit 48f5b32100c2c6977a76a317020ee319537ccbcd that the snake case naming is not propagating correctly.
Testing JSON inserted at the bottom of the template

### Steps to reproduce
To reproduce, have a test project referencing Telegram.Bot v13.3.0-rc1 and then call the following code
`string jsonInput = "<update-json-captured-from-telegram>";`
`Update testUpdateFromStringObj = Telegram.Bot.Types.Update.FromString(jsonInput);`
`Update testUpdateJsonConvObj = JsonConvert.DeserializeObject<Update>(jsonInput); `
`string jsonFromStringOutput = JsonConvert.SerializeObject(testUpdateFromStringObj);`
`string jsonJsonConvOutput = JsonConvert.SerializeObject(testUpdateJsonConvObj);`

### Expected  behavior
Both `testUpdateFromStringObj` and `testUpdateJsonConvObj` should be populated with all values from the given JSON.

### Actual behavior
JsonSerializationException is thrown with details:

> Newtonsoft.Json.JsonSerializationException occurred
  Message=Required property 'IsBot' not found in JSON. Path 'message.from', line 1, position 159.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Telegram.Bot.Types.Update.FromString(String data)

### Environment data
*NuGet Package Version:*
13.3.0-rc1

*.NET Version:*
.Net Framework 4.6.1

*IDE:*
VS2017

*App:*
WinForms and WebAPI

*Testing JSON*
The "from" section was manually changed to testing data, but the original gave the same error as this.

{"update_id":100,"message":{"message_id":8,"from":{"id":10050,"is_bot":false,"first_name":"Test","last_name":"User","username":"Testuser","language_code":"en"},"date":1511265251,"chat":{"id":10050,"type":"private","title":null,"username":"Test","first_name":"Testuser","last_name":"User","all_members_are_administrators":false,"photo":null,"description":null,"invite_link":null,"pinned_message":null},"forward_from":null,"forward_from_chat":null,"forward_from_message_id":0,"forward_signature":null,"forward_date":null,"reply_to_message":null,"edit_date":null,"author_signature":null,"text":"/testcommand","entities":[{"type":"bot_command","offset":0,"length":12,"url":null,"user":null}],"audio":null,"document":null,"game":null,"photo":null,"sticker":null,"video":null,"voice":null,"video_note":null,"caption":null,"contact":null,"location":null,"venue":null,"new_chat_member":null,"new_chat_members":null,"left_chat_member":null,"new_chat_title":null,"new_chat_photo":null,"delete_chat_photo":false,"group_chat_created":false,"supergroup_chat_created":false,"channel_chat_created":false,"migrate_to_chat_id":0,"migrate_from_chat_id":0,"pinned_message":null,"invoice":null,"successful_payment":null},"edited_message":null,"inline_query":null,"chosen_inline_result":null,"callback_query":null,"channel_post":null,"edited_channel_post":null,"shipping_query":null,"pre_checkout_query":null}

**Comment by Tuscen** [comment]
That definitely was caused by the latest update. We used global `SnakeCaseNamingStrategy` to get rid of excessive code in json related attributes. For now you can use one of the two solutions:

- You can change `ContractResolver` to custom contract resolver with `SnakeCaseNamingStrategy` in `JsonSerializerSettings` (in case of WebApi in old ASP.NET I believe it's somewhere in `GlobalConfiguration`)

If I'm not mistaken you can do it like this (and I can be mistaken because I've only used ASP.NET Core):
```csharp
var contractResolver = new DefaultContractResolver
{
    NamingStrategy = new SnakeCaseNamingStrategy()
}

GlobalConfiguration.Configuration.Formatters.JsonFormatter.SerializerSettings.ContractResolver = contractResolver;
```

But this solution will affect all json serialization in your project.

- Or you can take the update as string and deserialize it yourself passing `JsonSerializerSettings` instance.

```csharp
var settings = new JsonSerializerSettings
{
    ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new SnakeCaseNamingStrategy()
    }
}

Update update = JsonConvert.DeserializeObject<Update>(updateString, settings);
```

**Comment by Dragonsangel** [comment]
Thanks for the reply and suggestions for a workaround. I'll give it a shot later tonight.

I started with a potential fix where all the Type classes get their JsonObject attribute expanded with the NamingStrategyType=typeof(SnakeCaseNamingStrategy) attribute, which has worked sofar on my side in a test project.

Would that be the desired solve and if so, should I Branch > PR or Fork > PR?
Never sure which one which project uses
