### ISSUE TITLE
Server returned nothing (no headers, no data)

### ISSUE THREAD

**Issue by vblazhnov** [TelegramBots/Telegram.Bot#600]
### Steps to reproduce
1. Add OnReceiveGeneralError handler
2. Start bot

### Expected  behavior
Sometimes OnReceiveGeneralError handler calls with exception:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Server returned nothing (no headers, no data)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__124`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__55.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__124`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__55.MoveNext()
```

### Actual behavior
No exceptions

### Environment data

*NuGet Package Version:* 13.4.0

*.NET Version:* .NET Core 2.0

*IDE:* VS2017

*App:* asp.net core app

**Comment by pouladpld** [comment]
I never encountered that. How is your network setup? Proxy? Firewalls?

**Comment by vblazhnov** [comment]
Just NAT, no proxies, no additional firewalls.

Another functional works correctly and bot receive and send all messages from/to telegram.

And sometimes there are another exception in same handler:
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__124`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__55.MoveNext()
```

**Comment by pouladpld** [comment]
502 happens. It's from tg servers. You should guard against network exceptions anyways and this doesn't seem to be a bug report for our project.
