### ISSUE TITLE
Telegram bot down, Error 502 bad gateway

### ISSUE THREAD

**Issue by samuelg78** [TelegramBots/Telegram.Bot#676]
I cannot connect to the telegram bot, its return:

```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.Htt
pRequestException: Response status code does not indicate success: 502 (Bad Gate
way).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__121`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Telegram.Bot.Examples.Echo.Program.Main(String[] args) in D:\VisualStudio2
015\telegram.bot.examples-master\Telegram.Bot.Examples.Echo\Program.cs:line 78
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status
code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__121`1.MoveNext()<--
-
```

Seems like the outrage in europe have affected the bots. Is there any alternate gateway for connection to the bot?

**Comment by pouladpld** [comment]
@samuelg78 
Read [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md) and join our group [@tgbots_dotnet](https://t.me/tgbots_dotnet) if you have any questions.
