### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by erfan132** [TelegramBots/Telegram.Bot#736]
here is my source 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Telegram.Bot;

namespace proxy
{
    public partial class Form1 : Form
    {
       

        public Form1()
        {
            InitializeComponent();
            
           
        }

        private async void button1_Click(object sender, EventArgs e)
        {

            var webProxy = new WebProxy(new Uri("http://xxxxxxxxxxxx95"), BypassOnLocal: true);
            var bot = new TelegramBotClient("554109584:AAFbCYue8-9NXmZHHM0mMXaU5Q", webProxy);
            await bot.SendTextMessageAsync("118995327", "sadasd");
         
            bot.StartReceiving();
            bot.OnMessage += Bot_OnMessage1;

        }

        private async void Bot_OnMessage1(object sender, Telegram.Bot.Args.MessageEventArgs e)
        {
            MessageBox.Show(e.Message.Text);
            var webProxy = new WebProxy(new Uri("http://xxxxxx"), BypassOnLocal: true);
            var bot = new TelegramBotClient("554109584:AAFbCYue8-9NXmZHHM0mMXaU5nVO3evQN7Q", webProxy);
            await bot.SendTextMessageAsync(e.Message.Chat.Id, "ASDASD");
        }

    }
}
when i run it nothink happen 
error
Erfan(bio ro nega kon):
System.Reflection.TargetInvocationException was unhandled
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Delegate.DynamicInvokeImpl(Object[] args)
       at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
       at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
       at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at proxy.Program.Main() in C:\Users\erfan-PC\Documents\MEGAsync\proxy\proxy\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=An error occurred while sending the request.
       Source=mscorlib
       StackTrace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__51`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at proxy.Form1.<button1_Click>d__1.MoveNext() in C:\Users\erfan-PC\Documents\MEGAsync\proxy\proxy\Form1.cs:line 38
         --- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
       InnerException: 
            HResult=-2146233079
            Message=The underlying connection was closed: An unexpected error occurred on a send.
            Source=System
            StackTrace:
                 at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
                 at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
            InnerException: 
                 HResult=-2146232800
                 Message=Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
                 Source=System
                 StackTrace:
                      at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
                      at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
                      at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
                 InnerException: 
                      ErrorCode=10060
                      HResult=-2147467259
                      Message=A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
                      NativeErrorCode=10060
                      Source=System
                      StackTrace:
                           at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
                           at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                      InnerException:
socks5 protocol blocked in iran plz develop 
http proxy az good
actually a get breakpoint info

https://cdn.discordapp.com/attachments/444095523842949124/455771441263280128/IMG_20180611_210230_598.jpg 

https://cdn.discordapp.com/attachments/444095523842949124/455771440461905931/IMG_20180611_210221_339.jpg

**Comment by erfan132** [comment]
actually 
im use last version of freamwork 
and 
.net freamwork version 4.5

**Comment by erfan132** [comment]
man its not never going to fix??

**Comment by karb0f0s** [comment]
This error caused by your proxy configuration. We are not able neither reproduce nor fix this on our side. Please consult your proxy admin to fix.
