### ISSUE TITLE
Timeout error - System.Net.WebException: Unable to connect to the remote server

### ISSUE THREAD

**Issue by simongoldstone** [TelegramBots/Telegram.Bot#784]
I'm getting this error randomly in my error logs. Sometimes the message is successfully sent, other times it isn't.

Executing a simple `await Send...`

`System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 149.154.167.220:443

   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

   --- End of inner exception stack trace ---

   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)

   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

`

**Comment by pouladpld** [comment]
That is clearly a connection error. We can't do anything about it. 

Issue template is not followed. Join our  group on Telegram for further discussions.
