### ISSUE TITLE
Could not create SSL/TLS secure channe

### ISSUE THREAD

**Issue by jcmag** [TelegramBots/Telegram.Bot#809]
Hi,

My bot (http://t.me/TheFeedReaderBot) got this error from time to time:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__51`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TheFeedReaderBot.WebSite.WebhookController.<SendMessage>d__7.MoveNext() in D:\FeedReaderBot\TheFeedReaderBot.WebSite\WebHookController.cs:line 193
```

Do you have an idea of what could cause this error? (I see it once in a while in my log file...)

**Comment by karb0f0s** [comment]
If you found a bug in our library please follow [bug report](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/But_report.md) template and provide minimum reproducible example we can work on. If you have any other issues feel free to ask others about their experiences in dealing with such issues in our support chat.
[![telegram chat](https://img.shields.io/badge/Support_Chat-Telegram-blue.svg?style=flat-square)](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
