### ISSUE TITLE
Send a message on telegram: "Forbidden: bot is not a member of the supergroup chat"

### ISSUE THREAD

**Issue by paillave** [TelegramBots/Telegram.Bot#950]
I am trying to send a message on a chat on telegram.
I want telegram setups to be done only with the official UI as I want it to be possibly done by by an end user.

Here are telegram setup I do:
 - I created the bot `XXXXXXX_bot` with Botfather by getting the token: no problem
 - I created a Channel:
   - click "new channel"
   - channel name: `TestChannel`
   - click "Next"
   - select "Private channel"
   - click "Save"
   - Add my bot `XXXXXXX_bot`
   - Click "Make admin"
   - Click "Save"
 - I create the chat:
   - open the channel `TestChannel`
   - on the channel menu, select "Manage Channel"
   - click on "Add a group" in the discussion
   - click on "Create a new group"
   - group name: `TestChannelChat`
   - click "Create"
   - click "Save"
 - I add the bot to the new group:
   - open the group `TestChannelChat`
   - on the right panel, I click "add member"
   - Add my bot `XXXXXXX_bot`
   - click "Add"
   - right click on the newly added user in the chat and select "Promote to admin"
   - click "Save"

Here is the setup of admins of the channel:

[![enter image description here][2]][2]

At the end of the day, the setup of the chat/group is the following in the telegram UI:

[![enter image description here][1]][1]

Then I make my dotnet console application:
```shell
dotnet new console -o TestTelegram
dotnet add package Telegram.Bot
```

In `program.cs`, I put the following:
```csharp
using System;
using System.Threading.Tasks;
using Telegram.Bot;

namespace TestTelegram
{
    public static class Program
    {
        public static async Task Main()
        {
            var bot = new TelegramBotClient("XXXXXX MY BOT TOKEN XXXXXXXXXXX"); // No pb here
            var me = await bot.GetMeAsync(); // No pb here
            var chat = await bot.GetChatAsync("@TestChannelChat"); // No pb here
            await bot.SendTextMessageAsync(chat.Id, $"{me.Username} is awake"); // Exception is raised here!!!
            Console.ReadLine();
        }
    }
}
```
I get the following exception at the line the tries to send a message: `bot is not a member of the supergroup chat`

```
Exception has occurred: CLR/Telegram.Bot.Exceptions.ApiRequestException
An exception of type 'Telegram.Bot.Exceptions.ApiRequestException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Forbidden: bot is not a member of the supergroup chat'
   at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__54`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestTelegram.Program.<Main>d__0.MoveNext() in /home/stephane/Documents/Sources/TestTelegram/Program.cs:line 15
```

I also made the following (to bypass the actual chat and directly publish a message in the channel):

```csharp
using System;
using System.Threading.Tasks;
using Telegram.Bot;

namespace TestTelegram
{
    public static class Program
    {
        public static async Task Main()
        {
            var bot = new TelegramBotClient("XXXXXX MY BOT TOKEN XXXXXXXXXXX");
            var me = await bot.GetMeAsync();
            var chat = await bot.GetChatAsync("@TestChannel");
            await bot.SendTextMessageAsync(chat.Id, $"{me.Username} is awake");
            Console.ReadLine();
        }
    }
}
```

And I get the following exception instead (nearly the same): `bot is not a member of the channel chat`

```
Exception has occurred: CLR/Telegram.Bot.Exceptions.ApiRequestException
An exception of type 'Telegram.Bot.Exceptions.ApiRequestException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Forbidden: bot is not a member of the channel chat'
   at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__54`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestTelegram.Program.<Main>d__0.MoveNext() in /home/stephane/Documents/Sources/TestTelegram/Program.cs:line 15
```

One simple question: how to post a message on telegram with dotnet???

  [1]: https://i.stack.imgur.com/LY42m.jpg
  [2]: https://i.stack.imgur.com/HxWpb.jpg

**Comment by paillave** [comment]
the chat id should be recovered by getting last updates on the bot user.
